// Dữ liệu đầy đủ các tỉnh/thành phố, quận/huyện và phường/xã của Việt Nam

export interface Province {
    code: string
    name: string
    type: string
}

export interface District {
    code: string
    name: string
    type: string
    provinceCode: string
}

export interface Ward {
    code: string
    name: string
    type: string
    districtCode: string
}

export const vietnamProvinces: Province[] = [
    // Thành phố trực thuộc trung ương
    { code: "01", name: "Hà Nội", type: "thanh-pho" },
    { code: "79", name: "Thành phố Hồ Chí Minh", type: "thanh-pho" },
    { code: "48", name: "Đà Nẵng", type: "thanh-pho" },
    { code: "31", name: "Hải Phòng", type: "thanh-pho" },
    { code: "92", name: "Cần Thơ", type: "thanh-pho" },

    // Miền Bắc
    { code: "02", name: "Hà Giang", type: "tinh" },
    { code: "04", name: "Cao Bằng", type: "tinh" },
    { code: "06", name: "Bắc Kạn", type: "tinh" },
    { code: "08", name: "Tuyên Quang", type: "tinh" },
    { code: "10", name: "Lào Cai", type: "tinh" },
    { code: "11", name: "Điện Biên", type: "tinh" },
    { code: "12", name: "Lai Châu", type: "tinh" },
    { code: "14", name: "Sơn La", type: "tinh" },
    { code: "15", name: "Yên Bái", type: "tinh" },
    { code: "17", name: "Hoà Bình", type: "tinh" },
    { code: "19", name: "Thái Nguyên", type: "tinh" },
    { code: "20", name: "Lạng Sơn", type: "tinh" },
    { code: "22", name: "Quảng Ninh", type: "tinh" },
    { code: "24", name: "Bắc Giang", type: "tinh" },
    { code: "25", name: "Phú Thọ", type: "tinh" },
    { code: "26", name: "Vĩnh Phúc", type: "tinh" },
    { code: "27", name: "Bắc Ninh", type: "tinh" },
    { code: "30", name: "Hải Dương", type: "tinh" },
    { code: "33", name: "Hưng Yên", type: "tinh" },
    { code: "34", name: "Thái Bình", type: "tinh" },
    { code: "35", name: "Hà Nam", type: "tinh" },
    { code: "36", name: "Nam Định", type: "tinh" },
    { code: "37", name: "Ninh Bình", type: "tinh" },

    // Miền Trung
    { code: "38", name: "Thanh Hóa", type: "tinh" },
    { code: "40", name: "Nghệ An", type: "tinh" },
    { code: "42", name: "Hà Tĩnh", type: "tinh" },
    { code: "44", name: "Quảng Bình", type: "tinh" },
    { code: "45", name: "Quảng Trị", type: "tinh" },
    { code: "46", name: "Thừa Thiên Huế", type: "tinh" },
    { code: "49", name: "Quảng Nam", type: "tinh" },
    { code: "51", name: "Quảng Ngãi", type: "tinh" },
    { code: "52", name: "Bình Định", type: "tinh" },
    { code: "54", name: "Phú Yên", type: "tinh" },
    { code: "56", name: "Khánh Hòa", type: "tinh" },
    { code: "58", name: "Ninh Thuận", type: "tinh" },
    { code: "60", name: "Bình Thuận", type: "tinh" },
    { code: "62", name: "Kon Tum", type: "tinh" },
    { code: "64", name: "Gia Lai", type: "tinh" },
    { code: "66", name: "Đắk Lắk", type: "tinh" },
    { code: "67", name: "Đắk Nông", type: "tinh" },
    { code: "68", name: "Lâm Đồng", type: "tinh" },

    // Miền Nam
    { code: "70", name: "Bình Phước", type: "tinh" },
    { code: "72", name: "Tây Ninh", type: "tinh" },
    { code: "74", name: "Bình Dương", type: "tinh" },
    { code: "75", name: "Đồng Nai", type: "tinh" },
    { code: "77", name: "Bà Rịa - Vũng Tàu", type: "tinh" },
    { code: "80", name: "Long An", type: "tinh" },
    { code: "82", name: "Tiền Giang", type: "tinh" },
    { code: "83", name: "Bến Tre", type: "tinh" },
    { code: "84", name: "Trà Vinh", type: "tinh" },
    { code: "86", name: "Vĩnh Long", type: "tinh" },
    { code: "87", name: "Đồng Tháp", type: "tinh" },
    { code: "89", name: "An Giang", type: "tinh" },
    { code: "91", name: "Kiên Giang", type: "tinh" },
    { code: "93", name: "Hậu Giang", type: "tinh" },
    { code: "94", name: "Sóc Trăng", type: "tinh" },
    { code: "95", name: "Bạc Liêu", type: "tinh" },
    { code: "96", name: "Cà Mau", type: "tinh" },
]

export const vietnamDistricts: District[] = [
    // Hà Nội
    { code: "001", name: "Quận Ba Đình", type: "quan", provinceCode: "01" },
    { code: "002", name: "Quận Hoàn Kiếm", type: "quan", provinceCode: "01" },
    { code: "003", name: "Quận Tây Hồ", type: "quan", provinceCode: "01" },
    { code: "004", name: "Quận Long Biên", type: "quan", provinceCode: "01" },
    { code: "005", name: "Quận Cầu Giấy", type: "quan", provinceCode: "01" },
    { code: "006", name: "Quận Đống Đa", type: "quan", provinceCode: "01" },
    { code: "007", name: "Quận Hai Bà Trưng", type: "quan", provinceCode: "01" },
    { code: "008", name: "Quận Hoàng Mai", type: "quan", provinceCode: "01" },
    { code: "009", name: "Quận Thanh Xuân", type: "quan", provinceCode: "01" },
    { code: "016", name: "Huyện Sóc Sơn", type: "huyen", provinceCode: "01" },
    { code: "017", name: "Huyện Đông Anh", type: "huyen", provinceCode: "01" },
    { code: "018", name: "Huyện Gia Lâm", type: "huyen", provinceCode: "01" },
    { code: "019", name: "Quận Nam Từ Liêm", type: "quan", provinceCode: "01" },
    { code: "020", name: "Huyện Thanh Trì", type: "huyen", provinceCode: "01" },
    { code: "021", name: "Quận Bắc Từ Liêm", type: "quan", provinceCode: "01" },
    { code: "250", name: "Huyện Mê Linh", type: "huyen", provinceCode: "01" },
    { code: "268", name: "Quận Hà Đông", type: "quan", provinceCode: "01" },
    { code: "269", name: "Thị xã Sơn Tây", type: "thi-xa", provinceCode: "01" },
    { code: "271", name: "Huyện Ba Vì", type: "huyen", provinceCode: "01" },
    { code: "272", name: "Huyện Phúc Thọ", type: "huyen", provinceCode: "01" },
    { code: "273", name: "Huyện Đan Phượng", type: "huyen", provinceCode: "01" },
    { code: "274", name: "Huyện Hoài Đức", type: "huyen", provinceCode: "01" },
    { code: "275", name: "Huyện Quốc Oai", type: "huyen", provinceCode: "01" },
    { code: "276", name: "Huyện Thạch Thất", type: "huyen", provinceCode: "01" },
    { code: "277", name: "Huyện Chương Mỹ", type: "huyen", provinceCode: "01" },
    { code: "278", name: "Huyện Thanh Oai", type: "huyen", provinceCode: "01" },
    { code: "279", name: "Huyện Thường Tín", type: "huyen", provinceCode: "01" },
    { code: "280", name: "Huyện Phú Xuyên", type: "huyen", provinceCode: "01" },
    { code: "281", name: "Huyện Ứng Hòa", type: "huyen", provinceCode: "01" },
    { code: "282", name: "Huyện Mỹ Đức", type: "huyen", provinceCode: "01" },

    // TP Hồ Chí Minh
    { code: "760", name: "Quận 1", type: "quan", provinceCode: "79" },
    { code: "761", name: "Quận 12", type: "quan", provinceCode: "79" },
    { code: "764", name: "Quận Gò Vấp", type: "quan", provinceCode: "79" },
    { code: "765", name: "Quận Bình Thạnh", type: "quan", provinceCode: "79" },
    { code: "766", name: "Quận Tân Bình", type: "quan", provinceCode: "79" },
    { code: "767", name: "Quận Tân Phú", type: "quan", provinceCode: "79" },
    { code: "768", name: "Quận Phú Nhuận", type: "quan", provinceCode: "79" },
    { code: "769", name: "Thành phố Thủ Đức", type: "thanh-pho", provinceCode: "79" },
    { code: "770", name: "Quận 3", type: "quan", provinceCode: "79" },
    { code: "771", name: "Quận 10", type: "quan", provinceCode: "79" },
    { code: "772", name: "Quận 11", type: "quan", provinceCode: "79" },
    { code: "773", name: "Quận 4", type: "quan", provinceCode: "79" },
    { code: "774", name: "Quận 5", type: "quan", provinceCode: "79" },
    { code: "775", name: "Quận 6", type: "quan", provinceCode: "79" },
    { code: "776", name: "Quận 8", type: "quan", provinceCode: "79" },
    { code: "777", name: "Quận Bình Tân", type: "quan", provinceCode: "79" },
    { code: "778", name: "Quận 7", type: "quan", provinceCode: "79" },
    { code: "783", name: "Huyện Củ Chi", type: "huyen", provinceCode: "79" },
    { code: "784", name: "Huyện Hóc Môn", type: "huyen", provinceCode: "79" },
    { code: "785", name: "Huyện Bình Chánh", type: "huyen", provinceCode: "79" },
    { code: "786", name: "Huyện Nhà Bè", type: "huyen", provinceCode: "79" },
    { code: "787", name: "Huyện Cần Giờ", type: "huyen", provinceCode: "79" },

    // Đà Nẵng
    { code: "490", name: "Quận Hải Châu", type: "quan", provinceCode: "48" },
    { code: "491", name: "Quận Thanh Khê", type: "quan", provinceCode: "48" },
    { code: "492", name: "Quận Sơn Trà", type: "quan", provinceCode: "48" },
    { code: "493", name: "Quận Ngũ Hành Sơn", type: "quan", provinceCode: "48" },
    { code: "494", name: "Quận Liên Chiểu", type: "quan", provinceCode: "48" },
    { code: "495", name: "Quận Cẩm Lệ", type: "quan", provinceCode: "48" },
    { code: "497", name: "Huyện Hòa Vang", type: "huyen", provinceCode: "48" },
    { code: "498", name: "Huyện Hoàng Sa", type: "huyen", provinceCode: "48" },

    // Hải Phòng
    { code: "303", name: "Quận Hồng Bàng", type: "quan", provinceCode: "31" },
    { code: "304", name: "Quận Ngô Quyền", type: "quan", provinceCode: "31" },
    { code: "305", name: "Quận Lê Chân", type: "quan", provinceCode: "31" },
    { code: "306", name: "Quận Hải An", type: "quan", provinceCode: "31" },
    { code: "307", name: "Quận Kiến An", type: "quan", provinceCode: "31" },
    { code: "308", name: "Quận Đồ Sơn", type: "quan", provinceCode: "31" },
    { code: "309", name: "Quận Dương Kinh", type: "quan", provinceCode: "31" },
    { code: "311", name: "Huyện Thuỷ Nguyên", type: "huyen", provinceCode: "31" },
    { code: "312", name: "Huyện An Dương", type: "huyen", provinceCode: "31" },
    { code: "313", name: "Huyện An Lão", type: "huyen", provinceCode: "31" },
    { code: "314", name: "Huyện Kiến Thuỵ", type: "huyen", provinceCode: "31" },
    { code: "315", name: "Huyện Tiên Lãng", type: "huyen", provinceCode: "31" },
    { code: "316", name: "Huyện Vĩnh Bảo", type: "huyen", provinceCode: "31" },
    { code: "317", name: "Huyện Cát Hải", type: "huyen", provinceCode: "31" },
    { code: "318", name: "Huyện Bạch Long Vĩ", type: "huyen", provinceCode: "31" },

    // Cần Thơ
    { code: "916", name: "Quận Ninh Kiều", type: "quan", provinceCode: "92" },
    { code: "917", name: "Quận Ô Môn", type: "quan", provinceCode: "92" },
    { code: "918", name: "Quận Bình Thuỷ", type: "quan", provinceCode: "92" },
    { code: "919", name: "Quận Cái Răng", type: "quan", provinceCode: "92" },
    { code: "923", name: "Quận Thốt Nốt", type: "quan", provinceCode: "92" },
    { code: "924", name: "Huyện Vĩnh Thạnh", type: "huyen", provinceCode: "92" },
    { code: "925", name: "Huyện Cờ Đỏ", type: "huyen", provinceCode: "92" },
    { code: "926", name: "Huyện Phong Điền", type: "huyen", provinceCode: "92" },
    { code: "927", name: "Huyện Thới Lai", type: "huyen", provinceCode: "92" },
]

export const vietnamWards: Ward[] = [
    // Quận Ba Đình - Hà Nội
    { code: "00001", name: "Phường Phúc Xá", type: "phuong", districtCode: "001" },
    { code: "00004", name: "Phường Trúc Bạch", type: "phuong", districtCode: "001" },
    { code: "00006", name: "Phường Vĩnh Phúc", type: "phuong", districtCode: "001" },
    { code: "00007", name: "Phường Cống Vị", type: "phuong", districtCode: "001" },
    { code: "00008", name: "Phường Liễu Giai", type: "phuong", districtCode: "001" },
    { code: "00010", name: "Phường Nguyễn Trung Trực", type: "phuong", districtCode: "001" },
    { code: "00013", name: "Phường Quán Thánh", type: "phuong", districtCode: "001" },
    { code: "00016", name: "Phường Ngọc Hà", type: "phuong", districtCode: "001" },
    { code: "00019", name: "Phường Điện Biên", type: "phuong", districtCode: "001" },
    { code: "00022", name: "Phường Đội Cấn", type: "phuong", districtCode: "001" },
    { code: "00025", name: "Phường Ngọc Khánh", type: "phuong", districtCode: "001" },
    { code: "00028", name: "Phường Kim Mã", type: "phuong", districtCode: "001" },
    { code: "00031", name: "Phường Giảng Võ", type: "phuong", districtCode: "001" },
    { code: "00034", name: "Phường Thành Công", type: "phuong", districtCode: "001" },

    // Quận Hoàn Kiếm - Hà Nội
    { code: "00037", name: "Phường Phúc Tân", type: "phuong", districtCode: "002" },
    { code: "00040", name: "Phường Đồng Xuân", type: "phuong", districtCode: "002" },
    { code: "00043", name: "Phường Hàng Mã", type: "phuong", districtCode: "002" },
    { code: "00046", name: "Phường Hàng Buồm", type: "phuong", districtCode: "002" },
    { code: "00049", name: "Phường Hàng Đào", type: "phuong", districtCode: "002" },
    { code: "00052", name: "Phường Hàng Bồ", type: "phuong", districtCode: "002" },
    { code: "00055", name: "Phường Cửa Đông", type: "phuong", districtCode: "002" },
    { code: "00058", name: "Phường Lý Thái Tổ", type: "phuong", districtCode: "002" },
    { code: "00061", name: "Phường Hàng Bạc", type: "phuong", districtCode: "002" },
    { code: "00064", name: "Phường Hàng Gai", type: "phuong", districtCode: "002" },
    { code: "00067", name: "Phường Chương Dương Độ", type: "phuong", districtCode: "002" },
    { code: "00070", name: "Phường Hàng Trống", type: "phuong", districtCode: "002" },
    { code: "00073", name: "Phường Cửa Nam", type: "phuong", districtCode: "002" },
    { code: "00076", name: "Phường Hàng Bông", type: "phuong", districtCode: "002" },
    { code: "00079", name: "Phường Tràng Tiền", type: "phuong", districtCode: "002" },
    { code: "00082", name: "Phường Trần Hưng Đạo", type: "phuong", districtCode: "002" },
    { code: "00085", name: "Phường Phan Chu Trinh", type: "phuong", districtCode: "002" },
    { code: "00088", name: "Phường Hàng Bài", type: "phuong", districtCode: "002" },

    // Quận Tây Hồ - Hà Nội
    { code: "00091", name: "Phường Phú Thượng", type: "phuong", districtCode: "003" },
    { code: "00094", name: "Phường Nhật Tân", type: "phuong", districtCode: "003" },
    { code: "00097", name: "Phường Tứ Liên", type: "phuong", districtCode: "003" },
    { code: "00100", name: "Phường Quảng An", type: "phuong", districtCode: "003" },
    { code: "00103", name: "Phường Xuân La", type: "phuong", districtCode: "003" },
    { code: "00106", name: "Phường Yên Phụ", type: "phuong", districtCode: "003" },
    { code: "00109", name: "Phường Bưởi", type: "phuong", districtCode: "003" },
    { code: "00112", name: "Phường Thụy Khuê", type: "phuong", districtCode: "003" },

    // Quận Cầu Giấy - Hà Nội
    { code: "00172", name: "Phường Nghĩa Đô", type: "phuong", districtCode: "005" },
    { code: "00175", name: "Phường Nghĩa Tân", type: "phuong", districtCode: "005" },
    { code: "00178", name: "Phường Mai Dịch", type: "phuong", districtCode: "005" },
    { code: "00181", name: "Phường Dịch Vọng", type: "phuong", districtCode: "005" },
    { code: "00184", name: "Phường Dịch Vọng Hậu", type: "phuong", districtCode: "005" },
    { code: "00187", name: "Phường Quan Hoa", type: "phuong", districtCode: "005" },
    { code: "00190", name: "Phường Yên Hòa", type: "phuong", districtCode: "005" },
    { code: "00193", name: "Phường Trung Hòa", type: "phuong", districtCode: "005" },

    // Quận Đống Đa - Hà Nội
    { code: "00196", name: "Phường Cát Linh", type: "phuong", districtCode: "006" },
    { code: "00199", name: "Phường Văn Miếu", type: "phuong", districtCode: "006" },
    { code: "00202", name: "Phường Quốc Tử Giám", type: "phuong", districtCode: "006" },
    { code: "00205", name: "Phường Láng Thượng", type: "phuong", districtCode: "006" },
    { code: "00208", name: "Phường Ô Chợ Dừa", type: "phuong", districtCode: "006" },
    { code: "00211", name: "Phường Văn Chương", type: "phuong", districtCode: "006" },
    { code: "00214", name: "Phường Hàng Bột", type: "phuong", districtCode: "006" },
    { code: "00217", name: "Phường Láng Hạ", type: "phuong", districtCode: "006" },
    { code: "00220", name: "Phường Khâm Thiên", type: "phuong", districtCode: "006" },
    { code: "00223", name: "Phường Thổ Quan", type: "phuong", districtCode: "006" },
    { code: "00226", name: "Phường Nam Đồng", type: "phuong", districtCode: "006" },
    { code: "00229", name: "Phường Trung Phụng", type: "phuong", districtCode: "006" },
    { code: "00232", name: "Phường Quang Trung", type: "phuong", districtCode: "006" },
    { code: "00235", name: "Phường Trung Liệt", type: "phuong", districtCode: "006" },
    { code: "00238", name: "Phường Phương Liên", type: "phuong", districtCode: "006" },
    { code: "00241", name: "Phường Thịnh Quang", type: "phuong", districtCode: "006" },
    { code: "00244", name: "Phường Trung Tự", type: "phuong", districtCode: "006" },
    { code: "00247", name: "Phường Kim Liên", type: "phuong", districtCode: "006" },
    { code: "00250", name: "Phường Phương Mai", type: "phuong", districtCode: "006" },
    { code: "00253", name: "Phường Ngã Tư Sở", type: "phuong", districtCode: "006" },
    { code: "00256", name: "Phường Khương Thượng", type: "phuong", districtCode: "006" },

    // Quận 1 - TP HCM
    { code: "26734", name: "Phường Tân Định", type: "phuong", districtCode: "760" },
    { code: "26737", name: "Phường Đa Kao", type: "phuong", districtCode: "760" },
    { code: "26740", name: "Phường Bến Nghé", type: "phuong", districtCode: "760" },
    { code: "26743", name: "Phường Bến Thành", type: "phuong", districtCode: "760" },
    { code: "26746", name: "Phường Nguyễn Thái Bình", type: "phuong", districtCode: "760" },
    { code: "26749", name: "Phường Phạm Ngũ Lão", type: "phuong", districtCode: "760" },
    { code: "26752", name: "Phường Cầu Ông Lãnh", type: "phuong", districtCode: "760" },
    { code: "26755", name: "Phường Cô Giang", type: "phuong", districtCode: "760" },
    { code: "26758", name: "Phường Nguyễn Cư Trinh", type: "phuong", districtCode: "760" },
    { code: "26761", name: "Phường Cầu Kho", type: "phuong", districtCode: "760" },

    // Quận 3 - TP HCM
    { code: "26764", name: "Phường 1", type: "phuong", districtCode: "770" },
    { code: "26767", name: "Phường 2", type: "phuong", districtCode: "770" },
    { code: "26770", name: "Phường 3", type: "phuong", districtCode: "770" },
    { code: "26773", name: "Phường 4", type: "phuong", districtCode: "770" },
    { code: "26776", name: "Phường 5", type: "phuong", districtCode: "770" },
    { code: "26779", name: "Phường 6", type: "phuong", districtCode: "770" },
    { code: "26782", name: "Phường 7", type: "phuong", districtCode: "770" },
    { code: "26785", name: "Phường 8", type: "phuong", districtCode: "770" },
    { code: "26788", name: "Phường 9", type: "phuong", districtCode: "770" },
    { code: "26791", name: "Phường 10", type: "phuong", districtCode: "770" },
    { code: "26794", name: "Phường 11", type: "phuong", districtCode: "770" },
    { code: "26797", name: "Phường 12", type: "phuong", districtCode: "770" },
    { code: "26800", name: "Phường 13", type: "phuong", districtCode: "770" },
    { code: "26803", name: "Phường 14", type: "phuong", districtCode: "770" },

    // Quận Hải Châu - Đà Nẵng
    { code: "20194", name: "Phường Thạch Thang", type: "phuong", districtCode: "490" },
    { code: "20195", name: "Phường Hải Châu I", type: "phuong", districtCode: "490" },
    { code: "20197", name: "Phường Hải Châu II", type: "phuong", districtCode: "490" },
    { code: "20200", name: "Phường Phước Ninh", type: "phuong", districtCode: "490" },
    { code: "20203", name: "Phường Hòa Thuận Tây", type: "phuong", districtCode: "490" },
    { code: "20206", name: "Phường Hòa Thuận Đông", type: "phuong", districtCode: "490" },
    { code: "20207", name: "Phường Nam Dương", type: "phuong", districtCode: "490" },
    { code: "20209", name: "Phường Bình Hiên", type: "phuong", districtCode: "490" },
    { code: "20212", name: "Phường Bình Thuận", type: "phuong", districtCode: "490" },
    { code: "20215", name: "Phường Hòa Cường Bắc", type: "phuong", districtCode: "490" },
    { code: "20218", name: "Phường Hòa Cường Nam", type: "phuong", districtCode: "490" },
    { code: "20221", name: "Phường Thanh Bình", type: "phuong", districtCode: "490" },
    { code: "20224", name: "Phường Thuận Phước", type: "phuong", districtCode: "490" },

    // Quận Thanh Khê - Đà Nẵng
    { code: "20227", name: "Phường Tam Thuận", type: "phuong", districtCode: "491" },
    { code: "20230", name: "Phường Thanh Khê Tây", type: "phuong", districtCode: "491" },
    { code: "20233", name: "Phường Thanh Khê Đông", type: "phuong", districtCode: "491" },
    { code: "20236", name: "Phường Xuân Hà", type: "phuong", districtCode: "491" },
    { code: "20239", name: "Phường Tân Chính", type: "phuong", districtCode: "491" },
    { code: "20242", name: "Phường Chính Gián", type: "phuong", districtCode: "491" },
    { code: "20245", name: "Phường Vĩnh Trung", type: "phuong", districtCode: "491" },
    { code: "20246", name: "Phường Thạc Gián", type: "phuong", districtCode: "491" },
    { code: "20248", name: "Phường An Khê", type: "phuong", districtCode: "491" },
    { code: "20251", name: "Phường Hòa Khê", type: "phuong", districtCode: "491" },

    // Quận Hồng Bàng - Hải Phòng
    { code: "10117", name: "Phường Quán Toan", type: "phuong", districtCode: "303" },
    { code: "10120", name: "Phường Hùng Vương", type: "phuong", districtCode: "303" },
    { code: "10123", name: "Phường Sở Dầu", type: "phuong", districtCode: "303" },
    { code: "10126", name: "Phường Thượng Lý", type: "phuong", districtCode: "303" },
    { code: "10129", name: "Phường Hạ Lý", type: "phuong", districtCode: "303" },
    { code: "10132", name: "Phường Minh Khai", type: "phuong", districtCode: "303" },
    { code: "10135", name: "Phường Trại Cau", type: "phuong", districtCode: "303" },
    { code: "10138", name: "Phường Phan Bội Châu", type: "phuong", districtCode: "303" },
    { code: "10141", name: "Phường Hoàng Văn Thụ", type: "phuong", districtCode: "303" },

    // Quận Ninh Kiều - Cần Thơ
    { code: "31117", name: "Phường Cái Khế", type: "phuong", districtCode: "916" },
    { code: "31120", name: "Phường An Hòa", type: "phuong", districtCode: "916" },
    { code: "31123", name: "Phường Thới Bình", type: "phuong", districtCode: "916" },
    { code: "31126", name: "Phường An Nghiệp", type: "phuong", districtCode: "916" },
    { code: "31129", name: "Phường An Cư", type: "phuong", districtCode: "916" },
    { code: "31132", name: "Phường Tân An", type: "phuong", districtCode: "916" },
    { code: "31135", name: "Phường An Phú", type: "phuong", districtCode: "916" },
    { code: "31138", name: "Phường Xuân Khánh", type: "phuong", districtCode: "916" },
    { code: "31141", name: "Phường Hưng Lợi", type: "phuong", districtCode: "916" },
    { code: "31144", name: "Phường An Khánh", type: "phuong", districtCode: "916" },
    { code: "31147", name: "Phường An Bình", type: "phuong", districtCode: "916" },

    // Thêm các phường/xã khác cho các huyện nông thôn
    // Huyện Sóc Sơn - Hà Nội
    { code: "00466", name: "Thị trấn Sóc Sơn", type: "thi-tran", districtCode: "016" },
    { code: "00469", name: "Xã Bắc Sơn", type: "xa", districtCode: "016" },
    { code: "00472", name: "Xã Minh Trí", type: "xa", districtCode: "016" },
    { code: "00475", name: "Xã Hồng Kỳ", type: "xa", districtCode: "016" },
    { code: "00478", name: "Xã Nam Sơn", type: "xa", districtCode: "016" },
    { code: "00481", name: "Xã Trung Giã", type: "xa", districtCode: "016" },
    { code: "00484", name: "Xã Tân Hưng", type: "xa", districtCode: "016" },
    { code: "00487", name: "Xã Minh Phú", type: "xa", districtCode: "016" },
    { code: "00490", name: "Xã Phù Linh", type: "xa", districtCode: "016" },
    { code: "00493", name: "Xã Bắc Phú", type: "xa", districtCode: "016" },
    { code: "00496", name: "Xã Tân Minh", type: "xa", districtCode: "016" },
    { code: "00499", name: "Xã Quang Tiến", type: "xa", districtCode: "016" },
    { code: "00502", name: "Xã Hiền Ninh", type: "xa", districtCode: "016" },
    { code: "00505", name: "Xã Tân Dân", type: "xa", districtCode: "016" },
    { code: "00508", name: "Xã Tiên Dược", type: "xa", districtCode: "016" },
    { code: "00511", name: "Xã Việt Long", type: "xa", districtCode: "016" },
    { code: "00514", name: "Xã Xuân Giang", type: "xa", districtCode: "016" },
    { code: "00517", name: "Xã Mai Đình", type: "xa", districtCode: "016" },
    { code: "00520", name: "Xã Đức Hoà", type: "xa", districtCode: "016" },
    { code: "00523", name: "Xã Thanh Xuân", type: "xa", districtCode: "016" },
    { code: "00526", name: "Xã Đông Xuân", type: "xa", districtCode: "016" },
    { code: "00529", name: "Xã Kim Lũ", type: "xa", districtCode: "016" },
    { code: "00532", name: "Xã Phú Cường", type: "xa", districtCode: "016" },
    { code: "00535", name: "Xã Phú Minh", type: "xa", districtCode: "016" },
    { code: "00538", name: "Xã Phù Lỗ", type: "xa", districtCode: "016" },
    { code: "00541", name: "Xã Xuân Thu", type: "xa", districtCode: "016" },
    // Quận Long Biên - Hà Nội
    { code: "00115", name: "Phường Thượng Thanh", type: "phuong", districtCode: "004" },
    { code: "00118", name: "Phường Ngọc Thụy", type: "phuong", districtCode: "004" },
    { code: "00121", name: "Phường Giang Biên", type: "phuong", districtCode: "004" },
    { code: "00124", name: "Phường Đức Giang", type: "phuong", districtCode: "004" },
    { code: "00127", name: "Phường Việt Hưng", type: "phuong", districtCode: "004" },
    { code: "00130", name: "Phường Gia Thụy", type: "phuong", districtCode: "004" },
    { code: "00133", name: "Phường Ngọc Lâm", type: "phuong", districtCode: "004" },
    { code: "00136", name: "Phường Phúc Lợi", type: "phuong", districtCode: "004" },
    { code: "00139", name: "Phường Bồ Đề", type: "phuong", districtCode: "004" },
    { code: "00142", name: "Phường Sài Đồng", type: "phuong", districtCode: "004" },
    { code: "00145", name: "Phường Long Biên", type: "phuong", districtCode: "004" },
    { code: "00148", name: "Phường Thạch Bàn", type: "phuong", districtCode: "004" },
    { code: "00151", name: "Phường Phúc Đồng", type: "phuong", districtCode: "004" },
    { code: "00154", name: "Phường Cự Khối", type: "phuong", districtCode: "004" },

    // Quận Hai Bà Trưng - Hà Nội
    { code: "00259", name: "Phường Nguyễn Du", type: "phuong", districtCode: "007" },
    { code: "00262", name: "Phường Bạch Đằng", type: "phuong", districtCode: "007" },
    { code: "00265", name: "Phường Phạm Đình Hổ", type: "phuong", districtCode: "007" },
    { code: "00268", name: "Phường Lê Đại Hành", type: "phuong", districtCode: "007" },
    { code: "00271", name: "Phường Đồng Nhân", type: "phuong", districtCode: "007" },
    { code: "00274", name: "Phường Phố Huế", type: "phuong", districtCode: "007" },
    { code: "00277", name: "Phường Đống Mác", type: "phuong", districtCode: "007" },
    { code: "00280", name: "Phường Thanh Lương", type: "phuong", districtCode: "007" },
    { code: "00283", name: "Phường Thanh Nhàn", type: "phuong", districtCode: "007" },
    { code: "00286", name: "Phường Cầu Dền", type: "phuong", districtCode: "007" },
    { code: "00289", name: "Phường Bách Khoa", type: "phuong", districtCode: "007" },
    { code: "00292", name: "Phường Đồng Tâm", type: "phuong", districtCode: "007" },
    { code: "00295", name: "Phường Vĩnh Tuy", type: "phuong", districtCode: "007" },
    { code: "00298", name: "Phường Bạch Mai", type: "phuong", districtCode: "007" },
    { code: "00301", name: "Phường Quỳnh Mai", type: "phuong", districtCode: "007" },
    { code: "00304", name: "Phường Quỳnh Lôi", type: "phuong", districtCode: "007" },
    { code: "00307", name: "Phường Minh Khai", type: "phuong", districtCode: "007" },
    { code: "00310", name: "Phường Trương Định", type: "phuong", districtCode: "007" },

    // Quận Hoàng Mai - Hà Nội
    { code: "00313", name: "Phường Thanh Trì", type: "phuong", districtCode: "008" },
    { code: "00316", name: "Phường Vĩnh Hưng", type: "phuong", districtCode: "008" },
    { code: "00319", name: "Phường Định Công", type: "phuong", districtCode: "008" },
    { code: "00322", name: "Phường Mai Động", type: "phuong", districtCode: "008" },
    { code: "00325", name: "Phường Tương Mai", type: "phuong", districtCode: "008" },
    { code: "00328", name: "Phường Đại Kim", type: "phuong", districtCode: "008" },
    { code: "00331", name: "Phường Tân Mai", type: "phuong", districtCode: "008" },
    { code: "00334", name: "Phường Hoàng Văn Thụ", type: "phuong", districtCode: "008" },
    { code: "00337", name: "Phường Thinh Liệt", type: "phuong", districtCode: "008" },
    { code: "00340", name: "Phường Trần Phú", type: "phuong", districtCode: "008" },
    { code: "00343", name: "Phường Hoàng Liệt", type: "phuong", districtCode: "008" },
    { code: "00346", name: "Phường Yên Sở", type: "phuong", districtCode: "008" },
    { code: "00349", name: "Phường Giáp Bát", type: "phuong", districtCode: "008" },
    { code: "00352", name: "Phường Lĩnh Nam", type: "phuong", districtCode: "008" },

    // Quận Thanh Xuân - Hà Nội
    { code: "00355", name: "Phường Nhân Chính", type: "phuong", districtCode: "009" },
    { code: "00358", name: "Phường Thượng Đình", type: "phuong", districtCode: "009" },
    { code: "00361", name: "Phường Khương Trung", type: "phuong", districtCode: "009" },
    { code: "00364", name: "Phường Khương Đình", type: "phuong", districtCode: "009" },
    { code: "00367", name: "Phường Thanh Xuân Bắc", type: "phuong", districtCode: "009" },
    { code: "00370", name: "Phường Phương Liệt", type: "phuong", districtCode: "009" },
    { code: "00373", name: "Phường Hạ Đình", type: "phuong", districtCode: "009" },
    { code: "00376", name: "Phường Khương Mai", type: "phuong", districtCode: "009" },
    { code: "00379", name: "Phường Thanh Xuân Trung", type: "phuong", districtCode: "009" },
    { code: "00382", name: "Phường Thanh Xuân Nam", type: "phuong", districtCode: "009" },
    { code: "00385", name: "Phường Khương Thượng", type: "phuong", districtCode: "009" },

    // Quận Nam Từ Liêm - Hà Nội
    { code: "00388", name: "Phường Mễ Trì", type: "phuong", districtCode: "019" },
    { code: "00391", name: "Phường Phú Đô", type: "phuong", districtCode: "019" },
    { code: "00394", name: "Phường Tây Mỗ", type: "phuong", districtCode: "019" },
    { code: "00397", name: "Phường Xuân Phương", type: "phuong", districtCode: "019" },
    { code: "00400", name: "Phường Phương Canh", type: "phuong", districtCode: "019" },
    { code: "00403", name: "Phường Mỹ Đình 1", type: "phuong", districtCode: "019" },
    { code: "00406", name: "Phường Mỹ Đình 2", type: "phuong", districtCode: "019" },
    { code: "00409", name: "Phường Tân Phú", type: "phuong", districtCode: "019" },
    { code: "00412", name: "Phường Cầu Diễn", type: "phuong", districtCode: "019" },
    { code: "00415", name: "Phường Đại Mỗ", type: "phuong", districtCode: "019" },

    // Quận Bắc Từ Liêm - Hà Nội
    { code: "00418", name: "Phường Thượng Cát", type: "phuong", districtCode: "021" },
    { code: "00421", name: "Phường Liên Mạc", type: "phuong", districtCode: "021" },
    { code: "00424", name: "Phường Đông Ngạc", type: "phuong", districtCode: "021" },
    { code: "00427", name: "Phường Đức Thắng", type: "phuong", districtCode: "021" },
    { code: "00430", name: "Phường Thụy Phương", type: "phuong", districtCode: "021" },
    { code: "00433", name: "Phường Tây Tựu", type: "phuong", districtCode: "021" },
    { code: "00436", name: "Phường Xuân Đỉnh", type: "phuong", districtCode: "021" },
    { code: "00439", name: "Phường Xuân Tảo", type: "phuong", districtCode: "021" },
    { code: "00442", name: "Phường Minh Khai", type: "phuong", districtCode: "021" },
    { code: "00445", name: "Phường Cổ Nhuế 1", type: "phuong", districtCode: "021" },
    { code: "00448", name: "Phường Cổ Nhuế 2", type: "phuong", districtCode: "021" },
    { code: "00451", name: "Phường Phú Diễn", type: "phuong", districtCode: "021" },
    { code: "00454", name: "Phường Phúc Diễn", type: "phuong", districtCode: "021" },

    // Quận Hà Đông - Hà Nội
    { code: "09280", name: "Phường Nguyễn Trãi", type: "phuong", districtCode: "268" },
    { code: "09283", name: "Phường Mộ Lao", type: "phuong", districtCode: "268" },
    { code: "09286", name: "Phường Hà Cầu", type: "phuong", districtCode: "268" },
    { code: "09289", name: "Phường Yết Kiêu", type: "phuong", districtCode: "268" },
    { code: "09292", name: "Phường Quang Trung", type: "phuong", districtCode: "268" },
    { code: "09295", name: "Phường La Khê", type: "phuong", districtCode: "268" },
    { code: "09298", name: "Phường Phúc La", type: "phuong", districtCode: "268" },
    { code: "09301", name: "Phường Kiến Hưng", type: "phuong", districtCode: "268" },
    { code: "09304", name: "Phường Phú Lãm", type: "phuong", districtCode: "268" },
    { code: "09307", name: "Phường Phú Lương", type: "phuong", districtCode: "268" },
    { code: "09310", name: "Phường Dương Nội", type: "phuong", districtCode: "268" },
    { code: "09313", name: "Phường Đồng Mai", type: "phuong", districtCode: "268" },
    { code: "09316", name: "Phường Kiến Hưng", type: "phuong", districtCode: "268" },
    { code: "09319", name: "Phường Văn Quán", type: "phuong", districtCode: "268" },
    { code: "09322", name: "Phường Vạn Phúc", type: "phuong", districtCode: "268" },
    { code: "09325", name: "Phường Tô Hiệu", type: "phuong", districtCode: "268" },
    { code: "09328", name: "Phường Xuân Phương", type: "phuong", districtCode: "268" },
    { code: "09331", name: "Phường Biên Giang", type: "phuong", districtCode: "268" },

    // Huyện Đông Anh - Hà Nội
    { code: "00544", name: "Thị trấn Đông Anh", type: "thi-tran", districtCode: "017" },
    { code: "00547", name: "Xã Xuân Nộn", type: "xa", districtCode: "017" },
    { code: "00550", name: "Xã Thuỵ Lâm", type: "xa", districtCode: "017" },
    { code: "00553", name: "Xã Bắc Hồng", type: "xa", districtCode: "017" },
    { code: "00556", name: "Xã Nguyên Khê", type: "xa", districtCode: "017" },
    { code: "00559", name: "Xã Nam Hồng", type: "xa", districtCode: "017" },
    { code: "00562", name: "Xã Tiên Dương", type: "xa", districtCode: "017" },
    { code: "00565", name: "Xã Vân Hà", type: "xa", districtCode: "017" },
    { code: "00568", name: "Xã Uy Nỗ", type: "xa", districtCode: "017" },
    { code: "00571", name: "Xã Vân Nội", type: "xa", districtCode: "017" },
    { code: "00574", name: "Xã Liên Hà", type: "xa", districtCode: "017" },
    { code: "00577", name: "Xã Việt Hùng", type: "xa", districtCode: "017" },
    { code: "00580", name: "Xã Kim Nỗ", type: "xa", districtCode: "017" },
    { code: "00583", name: "Xã Kim Chung", type: "xa", districtCode: "017" },
    { code: "00586", name: "Xã Dục Tú", type: "xa", districtCode: "017" },
    { code: "00589", name: "Xã Đại Mạch", type: "xa", districtCode: "017" },
    { code: "00592", name: "Xã Vĩnh Ngọc", type: "xa", districtCode: "017" },
    { code: "00595", name: "Xã Cổ Loa", type: "xa", districtCode: "017" },
    { code: "00598", name: "Xã Hải Bối", type: "xa", districtCode: "017" },
    { code: "00601", name: "Xã Xuân Canh", type: "xa", districtCode: "017" },
    { code: "00604", name: "Xã Võng La", type: "xa", districtCode: "017" },
    { code: "00607", name: "Xã Tàm Xá", type: "xa", districtCode: "017" },
    { code: "00610", name: "Xã Mai Lâm", type: "xa", districtCode: "017" },

    // Huyện Gia Lâm - Hà Nội
    { code: "00613", name: "Thị trấn Trâu Quỳ", type: "thi-tran", districtCode: "018" },
    { code: "00616", name: "Xã Gia Lâm", type: "xa", districtCode: "018" },
    { code: "00619", name: "Xã Lệ Chi", type: "xa", districtCode: "018" },
    { code: "00622", name: "Xã Cần Kiệm", type: "xa", districtCode: "018" },
    { code: "00625", name: "Xã Ninh Hiệp", type: "xa", districtCode: "018" },
    { code: "00628", name: "Xã Đình Xuyên", type: "xa", districtCode: "018" },
    { code: "00631", name: "Xã Phù Đổng", type: "xa", districtCode: "018" },
    { code: "00634", name: "Xã Trung Mầu", type: "xa", districtCode: "018" },
    { code: "00637", name: "Xã Lệ Chi", type: "xa", districtCode: "018" },
    { code: "00640", name: "Xã Cổ Bi", type: "xa", districtCode: "018" },
    { code: "00643", name: "Xã Đặng Xá", type: "xa", districtCode: "018" },
    { code: "00646", name: "Xã Phú Thị", type: "xa", districtCode: "018" },
    { code: "00649", name: "Xã Kim Lan", type: "xa", districtCode: "018" },
    { code: "00652", name: "Xã Phú Thị", type: "xa", districtCode: "018" },
    { code: "00655", name: "Xã Yên Viên", type: "xa", districtCode: "018" },
    { code: "00658", name: "Xã Yên Thường", type: "xa", districtCode: "018" },
    { code: "00661", name: "Xã Yên Viên", type: "xa", districtCode: "018" },
    { code: "00664", name: "Xã Ninh Hiệp", type: "xa", districtCode: "018" },
    { code: "00667", name: "Xã Đông Dư", type: "xa", districtCode: "018" },
    { code: "00670", name: "Xã Đa Tốn", type: "xa", districtCode: "018" },
    { code: "00673", name: "Xã Kiêu Kỵ", type: "xa", districtCode: "018" },
    { code: "00676", name: "Xã Bát Tràng", type: "xa", districtCode: "018" },
    { code: "00679", name: "Xã Kim Chung", type: "xa", districtCode: "018" },

    // Huyện Thanh Trì - Hà Nội
    { code: "00682", name: "Thị trấn Văn Điển", type: "thi-tran", districtCode: "020" },
    { code: "00685", name: "Xã Tân Triều", type: "xa", districtCode: "020" },
    { code: "00688", name: "Xã Thanh Liệt", type: "xa", districtCode: "020" },
    { code: "00691", name: "Xã Tả Thanh Oai", type: "xa", districtCode: "020" },
    { code: "00694", name: "Xã Hữu Hòa", type: "xa", districtCode: "020" },
    { code: "00697", name: "Xã Tam Hiệp", type: "xa", districtCode: "020" },
    { code: "00700", name: "Xã Tứ Hiệp", type: "xa", districtCode: "020" },
    { code: "00703", name: "Xã Yên Mỹ", type: "xa", districtCode: "020" },
    { code: "00706", name: "Xã Vĩnh Quỳnh", type: "xa", districtCode: "020" },
    { code: "00709", name: "Xã Ngũ Hiệp", type: "xa", districtCode: "020" },
    { code: "00712", name: "Xã Duyên Hà", type: "xa", districtCode: "020" },
    { code: "00715", name: "Xã Ngọc Hồi", type: "xa", districtCode: "020" },
    { code: "00718", name: "Xã Vạn Phúc", type: "xa", districtCode: "020" },
    { code: "00721", name: "Xã Đại áng", type: "xa", districtCode: "020" },
    { code: "00724", name: "Xã Liên Ninh", type: "xa", districtCode: "020" },
    { code: "00727", name: "Xã Hạ Mỗ", type: "xa", districtCode: "020" },

    // Huyện Mê Linh - Hà Nội
    { code: "00730", name: "Thị trấn Chi Đông", type: "thi-tran", districtCode: "250" },
    { code: "00733", name: "Xã Đại Thịnh", type: "xa", districtCode: "250" },
    { code: "00736", name: "Xã Kim Hoa", type: "xa", districtCode: "250" },
    { code: "00739", name: "Xã Thạch Đà", type: "xa", districtCode: "250" },
    { code: "00742", name: "Xã Tiến Thắng", type: "xa", districtCode: "250" },
    { code: "00745", name: "Xã Tự Lập", type: "xa", districtCode: "250" },
    { code: "00748", name: "Xã Thụy Lôi", type: "xa", districtCode: "250" },
    { code: "00751", name: "Xã Lại Thượng", type: "xa", districtCode: "250" },
    { code: "00754", name: "Xã Liên Mạc", type: "xa", districtCode: "250" },
    { code: "00757", name: "Xã Vạn Yên", type: "xa", districtCode: "250" },
    { code: "00760", name: "Xã Chu Phan", type: "xa", districtCode: "250" },
    { code: "00763", name: "Xã Tiến Thịnh", type: "xa", districtCode: "250" },
    { code: "00766", name: "Xã Mê Linh", type: "xa", districtCode: "250" },
    { code: "00769", name: "Xã Văn Khê", type: "xa", districtCode: "250" },
    { code: "00772", name: "Xã Hoàng Kim", type: "xa", districtCode: "250" },
    { code: "00775", name: "Xã Tiền Phong", type: "xa", districtCode: "250" },
    { code: "00778", name: "Xã Tráng Việt", type: "xa", districtCode: "250" },
    { code: "00781", name: "Xã Quang Minh", type: "xa", districtCode: "250" },

    // Thị xã Sơn Tây - Hà Nội
    { code: "09334", name: "Phường Lê Lợi", type: "phuong", districtCode: "269" },
    { code: "09337", name: "Phường Phú Thịnh", type: "phuong", districtCode: "269" },
    { code: "09340", name: "Phường Ngô Quyền", type: "phuong", districtCode: "269" },
    { code: "09343", name: "Phường Quang Trung", type: "phuong", districtCode: "269" },
    { code: "09346", name: "Phường Sơn Lộc", type: "phuong", districtCode: "269" },
    { code: "09349", name: "Phường Xuân Khanh", type: "phuong", districtCode: "269" },
    { code: "09352", name: "Xã Đường Lâm", type: "xa", districtCode: "269" },
    { code: "09355", name: "Xã Xuân Sơn", type: "xa", districtCode: "269" },
    { code: "09358", name: "Xã Kim Lũ", type: "xa", districtCode: "269" },
    { code: "09361", name: "Xã Sơn Đông", type: "xa", districtCode: "269" },
    { code: "09364", name: "Xã Cổ Đông", type: "xa", districtCode: "269" },

    // Huyện Ba Vì - Hà Nội
    { code: "09367", name: "Thị trấn Tây Đằng", type: "thi-tran", districtCode: "271" },
    { code: "09370", name: "Xã Phú Cường", type: "xa", districtCode: "271" },
    { code: "09373", name: "Xã Cổ Đô", type: "xa", districtCode: "271" },
    { code: "09376", name: "Xã Tản Hồng", type: "xa", districtCode: "271" },
    { code: "09379", name: "Xã Vạn Thắng", type: "xa", districtCode: "271" },
    { code: "09382", name: "Xã Châu Sơn", type: "xa", districtCode: "271" },
    { code: "09385", name: "Xã Phong Vân", type: "xa", districtCode: "271" },
    { code: "09388", name: "Xã Phú Đông", type: "xa", districtCode: "271" },
    { code: "09391", name: "Xã Phú Phương", type: "xa", districtCode: "271" },
    { code: "09394", name: "Xã Phú Châu", type: "xa", districtCode: "271" },
    { code: "09397", name: "Xã Thái Hòa", type: "xa", districtCode: "271" },
    { code: "09400", name: "Xã Đồng Thái", type: "xa", districtCode: "271" },
    { code: "09403", name: "Xã Phú Sơn", type: "xa", districtCode: "271" },
    { code: "09406", name: "Xã Minh Châu", type: "xa", districtCode: "271" },
    { code: "09409", name: "Xã Vật Lại", type: "xa", districtCode: "271" },
    { code: "09412", name: "Xã Chu Minh", type: "xa", districtCode: "271" },
    { code: "09415", name: "Xã Tòng Bạt", type: "xa", districtCode: "271" },
    { code: "09418", name: "Xã Cẩm Lĩnh", type: "xa", districtCode: "271" },
    { code: "09421", name: "Xã Sơn Đà", type: "xa", districtCode: "271" },
    { code: "09424", name: "Xã Đông Quang", type: "xa", districtCode: "271" },
    { code: "09427", name: "Xã Tiên Phong", type: "xa", districtCode: "271" },
    { code: "09430", name: "Xã Thụy An", type: "xa", districtCode: "271" },
    { code: "09433", name: "Xã Cam Thượng", type: "xa", districtCode: "271" },
    { code: "09436", name: "Xã Thuần Mỹ", type: "xa", districtCode: "271" },
    { code: "09439", name: "Xã Tản Lĩnh", type: "xa", districtCode: "271" },
    { code: "09442", name: "Xã Ba Trại", type: "xa", districtCode: "271" },
    { code: "09445", name: "Xã Minh Quang", type: "xa", districtCode: "271" },
    { code: "09448", name: "Xã Ba Vì", type: "xa", districtCode: "271" },
    { code: "09451", name: "Xã Vân Hòa", type: "xa", districtCode: "271" },
    { code: "09454", name: "Xã Yên Bài", type: "xa", districtCode: "271" },
    { code: "09457", name: "Xã Khánh Thượng", type: "xa", districtCode: "271" },

    // Huyện Phúc Thọ - Hà Nội
    { code: "09460", name: "Thị trấn Phúc Thọ", type: "thi-tran", districtCode: "272" },
    { code: "09463", name: "Xã Vân Hà", type: "xa", districtCode: "272" },
    { code: "09466", name: "Xã Vân Phúc", type: "xa", districtCode: "272" },
    { code: "09469", name: "Xã Vân Nam", type: "xa", districtCode: "272" },
    { code: "09472", name: "Xã Xuân Đình", type: "xa", districtCode: "272" },
    { code: "09475", name: "Xã Sen Phương", type: "xa", districtCode: "272" },
    { code: "09478", name: "Xã Võng Xuyên", type: "xa", districtCode: "272" },
    { code: "09481", name: "Xã Thọ Lộc", type: "xa", districtCode: "272" },
    { code: "09484", name: "Xã Long Xuyên", type: "xa", districtCode: "272" },
    { code: "09487", name: "Xã Thượng Cốc", type: "xa", districtCode: "272" },
    { code: "09490", name: "Xã Hát Môn", type: "xa", districtCode: "272" },
    { code: "09493", name: "Xã Tích Giang", type: "xa", districtCode: "272" },
    { code: "09496", name: "Xã Thanh Đa", type: "xa", districtCode: "272" },
    { code: "09499", name: "Xã Trạch Mỹ Lộc", type: "xa", districtCode: "272" },
    { code: "09502", name: "Xã Phúc Hòa", type: "xa", districtCode: "272" },
    { code: "09505", name: "Xã Ngọc Tảo", type: "xa", districtCode: "272" },
    { code: "09508", name: "Xã Phụng Thượng", type: "xa", districtCode: "272" },
    { code: "09511", name: "Xã Tam Thuấn", type: "xa", districtCode: "272" },
    { code: "09514", name: "Xã Tam Hiệp", type: "xa", districtCode: "272" },
    { code: "09517", name: "Xã Hiệp Thuận", type: "xa", districtCode: "272" },
    { code: "09520", name: "Xã Liên Hiệp", type: "xa", districtCode: "272" },

    // Huyện Đan Phượng - Hà Nội
    { code: "09523", name: "Thị trấn Phùng", type: "thi-tran", districtCode: "273" },
    { code: "09526", name: "Xã Trung Châu", type: "xa", districtCode: "273" },
    { code: "09529", name: "Xã Thọ An", type: "xa", districtCode: "273" },
    { code: "09532", name: "Xã Thọ Xuân", type: "xa", districtCode: "273" },
    { code: "09535", name: "Xã Hồng Hà", type: "xa", districtCode: "273" },
    { code: "09538", name: "Xã Liên Hồng", type: "xa", districtCode: "273" },
    { code: "09541", name: "Xã Liên Hà", type: "xa", districtCode: "273" },
    { code: "09544", name: "Xã Hạ Mỗ", type: "xa", districtCode: "273" },
    { code: "09547", name: "Xã Liên Trung", type: "xa", districtCode: "273" },
    { code: "09550", name: "Xã Phương Đình", type: "xa", districtCode: "273" },
    { code: "09553", name: "Xã Thượng Mỗ", type: "xa", districtCode: "273" },
    { code: "09556", name: "Xã Tân Hội", type: "xa", districtCode: "273" },
    { code: "09559", name: "Xã Tân Lập", type: "xa", districtCode: "273" },
    { code: "09562", name: "Xã Đan Phượng", type: "xa", districtCode: "273" },
    { code: "09565", name: "Xã Đồng Tháp", type: "xa", districtCode: "273" },
    { code: "09568", name: "Xã Song Phượng", type: "xa", districtCode: "273" },

    // Huyện Hoài Đức - Hà Nội
    { code: "09571", name: "Thị trấn Trạm Trôi", type: "thi-tran", districtCode: "274" },
    { code: "09574", name: "Xã Đức Thượng", type: "xa", districtCode: "274" },
    { code: "09577", name: "Xã Minh Khai", type: "xa", districtCode: "274" },
    { code: "09580", name: "Xã Dương Liễu", type: "xa", districtCode: "274" },
    { code: "09583", name: "Xã Di Trạch", type: "xa", districtCode: "274" },
    { code: "09586", name: "Xã Đức Giang", type: "xa", districtCode: "274" },
    { code: "09589", name: "Xã Cát Quế", type: "xa", districtCode: "274" },
    { code: "09592", name: "Xã Kim Chung", type: "xa", districtCode: "274" },
    { code: "09595", name: "Xã Yên Sở", type: "xa", districtCode: "274" },
    { code: "09598", name: "Xã Sơn Đồng", type: "xa", districtCode: "274" },
    { code: "09601", name: "Xã Vân Canh", type: "xa", districtCode: "274" },
    { code: "09604", name: "Xã Đắc Sở", type: "xa", districtCode: "274" },
    { code: "09607", name: "Xã Lại Yên", type: "xa", districtCode: "274" },
    { code: "09610", name: "Xã Tiền Yên", type: "xa", districtCode: "274" },
    { code: "09613", name: "Xã Song Phương", type: "xa", districtCode: "274" },
    { code: "09616", name: "Xã An Khánh", type: "xa", districtCode: "274" },
    { code: "09619", name: "Xã An Thượng", type: "xa", districtCode: "274" },
    { code: "09622", name: "Xã Vân Côn", type: "xa", districtCode: "274" },
    { code: "09625", name: "Xã La Phù", type: "xa", districtCode: "274" },
    { code: "09628", name: "Xã Đông La", type: "xa", districtCode: "274" },

    // Huyện Quốc Oai - Hà Nội
    { code: "09631", name: "Thị trấn Quốc Oai", type: "thi-tran", districtCode: "275" },
    { code: "09634", name: "Xã Sài Sơn", type: "xa", districtCode: "275" },
    { code: "09637", name: "Xã Phượng Cách", type: "xa", districtCode: "275" },
    { code: "09640", name: "Xã Yên Sơn", type: "xa", districtCode: "275" },
    { code: "09643", name: "Xã Ngọc Liệp", type: "xa", districtCode: "275" },
    { code: "09646", name: "Xã Ngọc Mỹ", type: "xa", districtCode: "275" },
    { code: "09649", name: "Xã Liệp Tuyết", type: "xa", districtCode: "275" },
    { code: "09652", name: "Xã Thạch Thán", type: "xa", districtCode: "275" },
    { code: "09655", name: "Xã Đồng Quang", type: "xa", districtCode: "275" },
    { code: "09658", name: "Xã Phú Cát", type: "xa", districtCode: "275" },
    { code: "09661", name: "Xã Tuyết Nghĩa", type: "xa", districtCode: "275" },
    { code: "09664", name: "Xã Nghĩa Hương", type: "xa", districtCode: "275" },
    { code: "09667", name: "Xã Cộng Hòa", type: "xa", districtCode: "275" },
    { code: "09670", name: "Xã Tân Phú", type: "xa", districtCode: "275" },
    { code: "09673", name: "Xã Đại Thành", type: "xa", districtCode: "275" },
    { code: "09676", name: "Xã Phú Mãn", type: "xa", districtCode: "275" },
    { code: "09679", name: "Xã Cấn Hữu", type: "xa", districtCode: "275" },
    { code: "09682", name: "Xã Tân Hòa", type: "xa", districtCode: "275" },
    { code: "09685", name: "Xã Hòa Thạch", type: "xa", districtCode: "275" },
    { code: "09688", name: "Xã Đông Yên", type: "xa", districtCode: "275" },

    // Huyện Thạch Thất - Hà Nội
    { code: "09691", name: "Thị trấn Liên Quan", type: "thi-tran", districtCode: "276" },
    { code: "09694", name: "Xã Đại Đồng", type: "xa", districtCode: "276" },
    { code: "09697", name: "Xã Thạch Hoà", type: "xa", districtCode: "276" },
    { code: "09700", name: "Xã Cần Kiệm", type: "xa", districtCode: "276" },
    { code: "09703", name: "Xã Hữu Bằng", type: "xa", districtCode: "276" },
    { code: "09706", name: "Xã Thạch Thất", type: "xa", districtCode: "276" },
    { code: "09709", name: "Xã Thạch Xá", type: "xa", districtCode: "276" },
    { code: "09712", name: "Xã Bình Phú", type: "xa", districtCode: "276" },
    { code: "09715", name: "Xã Hạ Bằng", type: "xa", districtCode: "276" },
    { code: "09718", name: "Xã Thạch Trung", type: "xa", districtCode: "276" },
    { code: "09721", name: "Xã Kim Quan", type: "xa", districtCode: "276" },
    { code: "09724", name: "Xã Dị Nậu", type: "xa", districtCode: "276" },
    { code: "09727", name: "Xã Bình Yên", type: "xa", districtCode: "276" },
    { code: "09730", name: "Xã Chàng Sơn", type: "xa", districtCode: "276" },
    { code: "09733", name: "Xã Tam Đồng", type: "xa", districtCode: "276" },
    { code: "09736", name: "Xã Lại Thượng", type: "xa", districtCode: "276" },
    { code: "09739", name: "Xã Tân Xã", type: "xa", districtCode: "276" },
    { code: "09742", name: "Xã Yên Trung", type: "xa", districtCode: "276" },
    { code: "09745", name: "Xã Yên Bình", type: "xa", districtCode: "276" },
    { code: "09748", name: "Xã Tiến Xuân", type: "xa", districtCode: "276" },
    { code: "09751", name: "Xã Canh Nậu", type: "xa", districtCode: "276" },

    // Huyện Chương Mỹ - Hà Nội
    { code: "09754", name: "Thị trấn Chúc Sơn", type: "thi-tran", districtCode: "277" },
    { code: "09757", name: "Thị trấn Xuân Mai", type: "thi-tran", districtCode: "277" },
    { code: "09760", name: "Xã Phụng Châu", type: "xa", districtCode: "277" },
    { code: "09763", name: "Xã Tiên Phương", type: "xa", districtCode: "277" },
    { code: "09766", name: "Xã Đông Phương Yên", type: "xa", districtCode: "277" },
    { code: "09769", name: "Xã Phú Nghĩa", type: "xa", districtCode: "277" },
    { code: "09772", name: "Xã Trường Yên", type: "xa", districtCode: "277" },
    { code: "09775", name: "Xã Ngọc Hòa", type: "xa", districtCode: "277" },
    { code: "09778", name: "Xã Thủy Xuân Tiên", type: "xa", districtCode: "277" },
    { code: "09781", name: "Xã Thanh Bình", type: "xa", districtCode: "277" },
    { code: "09784", name: "Xã Trung Hòa", type: "xa", districtCode: "277" },
    { code: "09787", name: "Xã Đại Yên", type: "xa", districtCode: "277" },
    { code: "09790", name: "Xã Thụy Hương", type: "xa", districtCode: "277" },
    { code: "09793", name: "Xã Tốt Động", type: "xa", districtCode: "277" },
    { code: "09796", name: "Xã Lam Điền", type: "xa", districtCode: "277" },
    { code: "09799", name: "Xã Tân Tiến", type: "xa", districtCode: "277" },
    { code: "09802", name: "Xã Nam Phương Tiến", type: "xa", districtCode: "277" },
    { code: "09805", name: "Xã Hợp Đồng", type: "xa", districtCode: "277" },
    { code: "09808", name: "Xã Hoàng Văn Thụ", type: "xa", districtCode: "277" },
    { code: "09811", name: "Xã Hoàng Diệu", type: "xa", districtCode: "277" },
    { code: "09814", name: "Xã Hữu Văn", type: "xa", districtCode: "277" },
    { code: "09817", name: "Xã Quảng Bị", type: "xa", districtCode: "277" },
    { code: "09820", name: "Xã Mỹ Lương", type: "xa", districtCode: "277" },
    { code: "09823", name: "Xã Thượng Vực", type: "xa", districtCode: "277" },
    { code: "09826", name: "Xã Hồng Phong", type: "xa", districtCode: "277" },
    { code: "09829", name: "Xã Đồng Phú", type: "xa", districtCode: "277" },
    { code: "09832", name: "Xã Trần Phú", type: "xa", districtCode: "277" },
    { code: "09835", name: "Xã Văn Võ", type: "xa", districtCode: "277" },
    { code: "09838", name: "Xã Đồng Lạc", type: "xa", districtCode: "277" },
    { code: "09841", name: "Xã Hòa Chính", type: "xa", districtCode: "277" },
    { code: "09844", name: "Xã Phú Nam An", type: "xa", districtCode: "277" },

    // Huyện Thanh Oai - Hà Nội
    { code: "09847", name: "Thị trấn Kim Bài", type: "thi-tran", districtCode: "278" },
    { code: "09850", name: "Xã Cự Khê", type: "xa", districtCode: "278" },
    { code: "09853", name: "Xã Bích Hòa", type: "xa", districtCode: "278" },
    { code: "09856", name: "Xã Mỹ Hưng", type: "xa", districtCode: "278" },
    { code: "09859", name: "Xã Cao Viên", type: "xa", districtCode: "278" },
    { code: "09862", name: "Xã Bình Minh", type: "xa", districtCode: "278" },
    { code: "09865", name: "Xã Tam Hưng", type: "xa", districtCode: "278" },
    { code: "09868", name: "Xã Thanh Cao", type: "xa", districtCode: "278" },
    { code: "09871", name: "Xã Thanh Thùy", type: "xa", districtCode: "278" },
    { code: "09874", name: "Xã Thanh Mai", type: "xa", districtCode: "278" },
    { code: "09877", name: "Xã Thanh Văn", type: "xa", districtCode: "278" },
    { code: "09880", name: "Xã Đỗ Động", type: "xa", districtCode: "278" },
    { code: "09883", name: "Xã Kim An", type: "xa", districtCode: "278" },
    { code: "09886", name: "Xã Kim Thư", type: "xa", districtCode: "278" },
    { code: "09889", name: "Xã Phương Trung", type: "xa", districtCode: "278" },
    { code: "09892", name: "Xã Tân Ước", type: "xa", districtCode: "278" },
    { code: "09895", name: "Xã Dân Hòa", type: "xa", districtCode: "278" },
    { code: "09898", name: "Xã Liên Châu", type: "xa", districtCode: "278" },
    { code: "09901", name: "Xã Cao Dương", type: "xa", districtCode: "278" },
    { code: "09904", name: "Xã Xuân Dương", type: "xa", districtCode: "278" },
    { code: "09907", name: "Xã Hồng Dương", type: "xa", districtCode: "278" },

    // Huyện Thường Tín - Hà Nội
    { code: "09910", name: "Thị trấn Thường Tín", type: "thi-tran", districtCode: "279" },
    { code: "09913", name: "Xã Ninh Sở", type: "xa", districtCode: "279" },
    { code: "09916", name: "Xã Nhị Khê", type: "xa", districtCode: "279" },
    { code: "09919", name: "Xã Duyên Thái", type: "xa", districtCode: "279" },
    { code: "09922", name: "Xã Khánh Hà", type: "xa", districtCode: "279" },
    { code: "09925", name: "Xã Hòa Bình", type: "xa", districtCode: "279" },
    { code: "09928", name: "Xã Văn Bình", type: "xa", districtCode: "279" },
    { code: "09931", name: "Xã Hiền Giang", type: "xa", districtCode: "279" },
    { code: "09934", name: "Xã Hồng Vân", type: "xa", districtCode: "279" },
    { code: "09937", name: "Xã Vân Tảo", type: "xa", districtCode: "279" },
    { code: "09940", name: "Xã Liên Phương", type: "xa", districtCode: "279" },
    { code: "09943", name: "Xã Văn Phú", type: "xa", districtCode: "279" },
    { code: "09946", name: "Xã Tự Nhiên", type: "xa", districtCode: "279" },
    { code: "09949", name: "Xã Tiền Phong", type: "xa", districtCode: "279" },
    { code: "09952", name: "Xã Hà Hồi", type: "xa", districtCode: "279" },
    { code: "09955", name: "Xã Thư Phú", type: "xa", districtCode: "279" },
    { code: "09958", name: "Xã Nguyễn Trãi", type: "xa", districtCode: "279" },
    { code: "09961", name: "Xã Quất Động", type: "xa", districtCode: "279" },
    { code: "09964", name: "Xã Chương Dương", type: "xa", districtCode: "279" },
    { code: "09967", name: "Xã Tân Minh", type: "xa", districtCode: "279" },
    { code: "09970", name: "Xã Lê Lợi", type: "xa", districtCode: "279" },
    { code: "09973", name: "Xã Thắng Lợi", type: "xa", districtCode: "279" },
    { code: "09976", name: "Xã Dũng Tiến", type: "xa", districtCode: "279" },
    { code: "09979", name: "Xã Thống Nhất", type: "xa", districtCode: "279" },
    { code: "09982", name: "Xã Nghiêm Xuyên", type: "xa", districtCode: "279" },
    { code: "09985", name: "Xã Tô Hiệu", type: "xa", districtCode: "279" },
    { code: "09988", name: "Xã Văn Tự", type: "xa", districtCode: "279" },
    { code: "09991", name: "Xã Vạn Điểm", type: "xa", districtCode: "279" },
    { code: "09994", name: "Xã Minh Cường", type: "xa", districtCode: "279" },

    // Huyện Phú Xuyên - Hà Nội
    { code: "09997", name: "Thị trấn Phú Minh", type: "thi-tran", districtCode: "280" },
    { code: "10000", name: "Thị trấn Phú Xuyên", type: "thi-tran", districtCode: "280" },
    { code: "10003", name: "Xã Hồng Minh", type: "xa", districtCode: "280" },
    { code: "10006", name: "Xã Phượng Dực", type: "xa", districtCode: "280" },
    { code: "10009", name: "Xã Nam Tiến", type: "xa", districtCode: "280" },
    { code: "10012", name: "Xã Tri Trung", type: "xa", districtCode: "280" },
    { code: "10015", name: "Xã Đại Thắng", type: "xa", districtCode: "280" },
    { code: "10018", name: "Xã Phú Túc", type: "xa", districtCode: "280" },
    { code: "10021", name: "Xã Văn Hoàng", type: "xa", districtCode: "280" },
    { code: "10024", name: "Xã Hồng Thái", type: "xa", districtCode: "280" },
    { code: "10027", name: "Xã Hoàng Long", type: "xa", districtCode: "280" },
    { code: "10030", name: "Xã Quang Trung", type: "xa", districtCode: "280" },
    { code: "10033", name: "Xã Phú Yên", type: "xa", districtCode: "280" },
    { code: "10036", name: "Xã Hạ Mỗ", type: "xa", districtCode: "280" },
    { code: "10039", name: "Xã Sơn Hà", type: "xa", districtCode: "280" },
    { code: "10042", name: "Xã Chuyên Mỹ", type: "xa", districtCode: "280" },
    { code: "10045", name: "Xã Khai Thái", type: "xa", districtCode: "280" },
    { code: "10048", name: "Xã Phúc Tiến", type: "xa", districtCode: "280" },
    { code: "10051", name: "Xã Vân Từ", type: "xa", districtCode: "280" },
    { code: "10054", name: "Xã Tri Thủy", type: "xa", districtCode: "280" },
    { code: "10057", name: "Xã Đại Xuân", type: "xa", districtCode: "280" },
    { code: "10060", name: "Xã Phú Lương", type: "xa", districtCode: "280" },
    { code: "10063", name: "Xã Châu Can", type: "xa", districtCode: "280" },
    { code: "10066", name: "Xã Minh Tân", type: "xa", districtCode: "280" },

    // Huyện Ứng Hòa - Hà Nội
    { code: "10069", name: "Thị trấn Vân Đình", type: "thi-tran", districtCode: "281" },
    { code: "10072", name: "Xã Viên An", type: "xa", districtCode: "281" },
    { code: "10075", name: "Xã Viên Nội", type: "xa", districtCode: "281" },
    { code: "10078", name: "Xã Hoa Sơn", type: "xa", districtCode: "281" },
    { code: "10081", name: "Xã Quảng Phú Cầu", type: "xa", districtCode: "281" },
    { code: "10084", name: "Xã Trường Thịnh", type: "xa", districtCode: "281" },
    { code: "10087", name: "Xã Cao Thành", type: "xa", districtCode: "281" },
    { code: "10090", name: "Xã Liên Bạt", type: "xa", districtCode: "281" },
    { code: "10093", name: "Xã Trung Tú", type: "xa", districtCode: "281" },
    { code: "10096", name: "Xã Tảo Dương Văn", type: "xa", districtCode: "281" },
    { code: "10099", name: "Xã Hồng Quang", type: "xa", districtCode: "281" },
    { code: "10102", name: "Xã Đồng Tân", type: "xa", districtCode: "281" },
    { code: "10105", name: "Xã Tân Công Sính", type: "xa", districtCode: "281" },
    { code: "10108", name: "Xã Thạch Quý", type: "xa", districtCode: "281" },
    { code: "10111", name: "Xã Đại Cường", type: "xa", districtCode: "281" },
    { code: "10114", name: "Xã Đông Lỗ", type: "xa", districtCode: "281" },
    { code: "10117", name: "Xã Phù Lưu", type: "xa", districtCode: "281" },
    { code: "10120", name: "Xã Đại Hưng", type: "xa", districtCode: "281" },
    { code: "10123", name: "Xã Phù Lưu Tế", type: "xa", districtCode: "281" },
    { code: "10126", name: "Xã Hòa Lâm", type: "xa", districtCode: "281" },
    { code: "10129", name: "Xã Hòa Xá", type: "xa", districtCode: "281" },
    { code: "10132", name: "Xã Trầm Lộng", type: "xa", districtCode: "281" },
    { code: "10135", name: "Xã Kim Đường", type: "xa", districtCode: "281" },
    { code: "10138", name: "Xã Hoa Thủy", type: "xa", districtCode: "281" },
    { code: "10141", name: "Xã Hồng Phong", type: "xa", districtCode: "281" },
    { code: "10144", name: "Xã Dương Đình", type: "xa", districtCode: "281" },
    { code: "10147", name: "Xã Phương Tú", type: "xa", districtCode: "281" },
    { code: "10150", name: "Xã Trung Nghĩa", type: "xa", districtCode: "281" },
    { code: "10153", name: "Xã Lưu Hoàng", type: "xa", districtCode: "281" },
    { code: "10156", name: "Xã Hồng Phú", type: "xa", districtCode: "281" },
    { code: "10159", name: "Xã Đội Bình", type: "xa", districtCode: "281" },
    { code: "10162", name: "Xã Đại Hùng", type: "xa", districtCode: "281" },
    { code: "10165", name: "Xã Bình Dương", type: "xa", districtCode: "281" },
    { code: "10168", name: "Xã Lưu Tân", type: "xa", districtCode: "281" },
    { code: "10171", name: "Xã Chàm Puông", type: "xa", districtCode: "281" },

    // Huyện Mỹ Đức - Hà Nội
    { code: "10174", name: "Thị trấn Đại Nghĩa", type: "thi-tran", districtCode: "282" },
    { code: "10177", name: "Xã Đồng Tâm", type: "xa", districtCode: "282" },
    { code: "10180", name: "Xã Thượng Lâm", type: "xa", districtCode: "282" },
    { code: "10183", name: "Xã Tuy Lai", type: "xa", districtCode: "282" },
    { code: "10186", name: "Xã Phúc Lâm", type: "xa", districtCode: "282" },
    { code: "10189", name: "Xã Mỹ Thành", type: "xa", districtCode: "282" },
    { code: "10192", name: "Xã Bột Xuyên", type: "xa", districtCode: "282" },
    { code: "10195", name: "Xã An Mỹ", type: "xa", districtCode: "282" },
    { code: "10198", name: "Xã Hồng Sơn", type: "xa", districtCode: "282" },
    { code: "10201", name: "Xã Lê Thanh", type: "xa", districtCode: "282" },
    { code: "10204", name: "Xã Xuy Xá", type: "xa", districtCode: "282" },
    { code: "10207", name: "Xã Phùng Xá", type: "xa", districtCode: "282" },
    { code: "10210", name: "Xã Phù Lưu Tế", type: "xa", districtCode: "282" },
    { code: "10213", name: "Xã Đại Hưng", type: "xa", districtCode: "282" },
    { code: "10216", name: "Xã Vạn Kim", type: "xa", districtCode: "282" },
    { code: "10219", name: "Xã Đốc Tín", type: "xa", districtCode: "282" },
    { code: "10222", name: "Xã Hương Sơn", type: "xa", districtCode: "282" },
    { code: "10225", name: "Xã Hùng Tiến", type: "xa", districtCode: "282" },
    { code: "10228", name: "Xã An Tiến", type: "xa", districtCode: "282" },
    { code: "10231", name: "Xã Hợp Tiến", type: "xa", districtCode: "282" },
    { code: "10234", name: "Xã Hợp Thanh", type: "xa", districtCode: "282" },
    { code: "10237", name: "Xã An Phú", type: "xa", districtCode: "282" },
]

export function getDistrictsByProvince(provinceCode: string): District[] {
    return vietnamDistricts.filter((district) => district.provinceCode === provinceCode)
}

export function getWardsByDistrict(districtCode: string): Ward[] {
    return vietnamWards.filter((ward) => ward.districtCode === districtCode)
}

export function getProvinceByCode(code: string): Province | undefined {
    return vietnamProvinces.find((province) => province.code === code)
}

export function getDistrictByCode(code: string): District | undefined {
    return vietnamDistricts.find((district) => district.code === code)
}

export function getWardByCode(code: string): Ward | undefined {
    return vietnamWards.find((ward) => ward.code === code)
}

export function getFullAddressString(
    provinceCode: string,
    districtCode: string,
    wardCode: string,
    detailedAddress?: string,
): string {
    const province = getProvinceByCode(provinceCode)
    const district = getDistrictByCode(districtCode)
    const ward = getWardByCode(wardCode)

    const parts = []
    if (detailedAddress) parts.push(detailedAddress)
    if (ward) parts.push(ward.name)
    if (district) parts.push(district.name)
    if (province) parts.push(province.name)

    return parts.join(", ")
}
